
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author erickgamer
 */
public class TelaCampeao extends javax.swing.JFrame {

    /**
     * Creates new form TelaCampeao
     */
    public TelaCampeao() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
         
    }

   public  TelaCampeao(String jogadorA, String jogadorB, String pontosA, String pontosB) {
        
       
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        nomedojogadormarinheiro.setText(jogadorA.toString());
        nomedojogadorpirata.setText(jogadorB.toString());
        receberpontosjogador1.setText(pontosA.toString());
        receberpontosjogador2.setText(pontosB.toString());
        
        
          if(Integer.valueOf(pontosA)>Integer.valueOf(pontosB))
                    campeao.setText(jogadorA);
                          else {
                                if(Integer.valueOf(pontosA) <Integer.valueOf(pontosB)){
                                    campeao.setText(jogadorB);
                                    
                                } else{
                                           campeao.setText("JOGO EMPATADO!"); 
                                            }
                                    
                                    
                                    
                                
        
        
    }
   }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        labelnomedojogador1 = new javax.swing.JLabel();
        labelnomejogador2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        campeao = new javax.swing.JLabel();
        nomedojogadorpirata = new javax.swing.JLabel();
        nomedojogadormarinheiro = new javax.swing.JLabel();
        receberpontosjogador1 = new javax.swing.JLabel();
        receberpontosjogador2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jogador1 = new javax.swing.JTextArea();
        buttonfecharojogo = new javax.swing.JButton();
        buttonvoltarparaomenu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setText("Placar final");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(560, 220, 150, 40);

        labelnomedojogador1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        labelnomedojogador1.setText("Marinheiro");
        jPanel1.add(labelnomedojogador1);
        labelnomedojogador1.setBounds(500, 330, 70, 15);

        labelnomejogador2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        labelnomejogador2.setText("Pirata");
        jPanel1.add(labelnomejogador2);
        labelnomejogador2.setBounds(500, 400, 60, 15);

        jLabel5.setText("Pontuação");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(750, 290, 70, 14);

        jLabel6.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        jLabel6.setText("O campeão foi:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(570, 460, 120, 15);

        campeao.setText("nome do jogador campeao");
        campeao.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                campeaoAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel1.add(campeao);
        campeao.setBounds(570, 480, 260, 14);

        nomedojogadorpirata.setText("jLabel7");
        jPanel1.add(nomedojogadorpirata);
        nomedojogadorpirata.setBounds(500, 420, 250, 14);

        nomedojogadormarinheiro.setText("jLabel3");
        nomedojogadormarinheiro.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                nomedojogadormarinheiroAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel1.add(nomedojogadormarinheiro);
        nomedojogadormarinheiro.setBounds(500, 350, 230, 14);

        receberpontosjogador1.setText("x");
        receberpontosjogador1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                receberpontosjogador1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel1.add(receberpontosjogador1);
        receberpontosjogador1.setBounds(776, 340, 30, 14);

        receberpontosjogador2.setText("y");
        receberpontosjogador2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                receberpontosjogador2AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel1.add(receberpontosjogador2);
        receberpontosjogador2.setBounds(776, 420, 30, 14);

        jogador1.setEditable(false);
        jogador1.setBackground(new java.awt.Color(204, 204, 204));
        jogador1.setColumns(20);
        jogador1.setRows(5);
        jogador1.setToolTipText("");
        jogador1.setEnabled(false);
        jScrollPane1.setViewportView(jogador1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(440, 210, 420, 320);

        buttonfecharojogo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        buttonfecharojogo.setText("Fechar o jogo");
        buttonfecharojogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonfecharojogoActionPerformed(evt);
            }
        });
        jPanel1.add(buttonfecharojogo);
        buttonfecharojogo.setBounds(900, 610, 240, 30);

        buttonvoltarparaomenu.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        buttonvoltarparaomenu.setText("Voltar para o menu principal");
        buttonvoltarparaomenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonvoltarparaomenuActionPerformed(evt);
            }
        });
        jPanel1.add(buttonvoltarparaomenu);
        buttonvoltarparaomenu.setBounds(640, 610, 240, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assassins_creed_iv_black_flag_7-wallpaper-2400x1350.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(-190, 10, 1990, 1210);

        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(510, 420, 34, 14);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, -20, 1850, 1240);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonvoltarparaomenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonvoltarparaomenuActionPerformed
       new ShipRoyale03().setVisible(true);
this.dispose();
    }//GEN-LAST:event_buttonvoltarparaomenuActionPerformed

    private void buttonfecharojogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonfecharojogoActionPerformed
     int resposta = JOptionPane.showConfirmDialog(null, "Deseja mesmo sair do jogo??", "Exit", JOptionPane.YES_NO_OPTION);
        if (resposta == JOptionPane.YES_OPTION) {
            System.exit(0);// Seu código caso SIM
        }
    }//GEN-LAST:event_buttonfecharojogoActionPerformed

    private void nomedojogadormarinheiroAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_nomedojogadormarinheiroAncestorAdded
        
    }//GEN-LAST:event_nomedojogadormarinheiroAncestorAdded

    private void receberpontosjogador1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_receberpontosjogador1AncestorAdded

    }//GEN-LAST:event_receberpontosjogador1AncestorAdded

    private void receberpontosjogador2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_receberpontosjogador2AncestorAdded
      
    }//GEN-LAST:event_receberpontosjogador2AncestorAdded

    private void campeaoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_campeaoAncestorAdded
          
    }//GEN-LAST:event_campeaoAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCampeao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCampeao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCampeao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCampeao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCampeao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonfecharojogo;
    private javax.swing.JButton buttonvoltarparaomenu;
    public static javax.swing.JLabel campeao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jogador1;
    private javax.swing.JLabel labelnomedojogador1;
    private javax.swing.JLabel labelnomejogador2;
    private javax.swing.JLabel nomedojogadormarinheiro;
    private javax.swing.JLabel nomedojogadorpirata;
    public static javax.swing.JLabel receberpontosjogador1;
    private javax.swing.JLabel receberpontosjogador2;
    // End of variables declaration//GEN-END:variables
}
