/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author aluno
 */
public class Telainstrucoes extends javax.swing.JFrame {

    /**
     * Creates new form Telainstrucoes
     */
    public Telainstrucoes() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Areadetexto = new java.awt.TextArea();
        button_voltarparaomenu = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        Areadetexto.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Areadetexto.setEditable(false);
        Areadetexto.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Areadetexto.setName(""); // NOI18N
        Areadetexto.setText("                                                      Instruções\n\nO jogo SHIP ROYALE é uma adaptação do jogo clássico que inclui novas regras e mais\nestratégia. Este jogo é jogado por 2 jogadores, cada um por si, com apenas um único\ntabuleiro.\n•\tJogadores - 2\n•\tTabuleiro   - 1 tabuleiro 10x10 (10 linhas e 10 colunas )\n•\tBarcos:\n\no\t5 Submarinos;\no\t4 Destroyers;\no\t3 Cruzadores;\no\t2 Navios;\no\t1 Porta-Aviões;\n\nO jogo começa pedindo o nome dos dois jogadores, um nickname podendo conter numeros e letras.\n Logo após a escolha de Nicks, é apresentado o tabuleiro que, de forma aleatória, possui\n vários barcos diferentes.O objetivo principal do jogo é acertar com tiros, o máximo de partes \nde barcos possíveis para acumular pontos. Cada jogador possui 1 tiro por turno. O jogo acaba \nquando não há mais lugar no tabuleiro para dar tiros ou quando os jogadores desejarem\n sair. A contabilização de pontos é feita por quantidade de acertos de tiros em barcos.\n Cada acerto em uma parte de barco é somado 1 ponto para o jogador que realizou o tiro.\n É utilizado o botão esquerdo do mouse para realizar os tiros. No final do jogo é apresentado\no placar final dos jogadores e qual dos jogadores foi o campeão.\nDivirta-se jogando o SHIP ROYALE!!!");
        getContentPane().add(Areadetexto);
        Areadetexto.setBounds(430, 30, 900, 630);

        button_voltarparaomenu.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        button_voltarparaomenu.setText("Voltar para o menu");
        button_voltarparaomenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_voltarparaomenuActionPerformed(evt);
            }
        });
        getContentPane().add(button_voltarparaomenu);
        button_voltarparaomenu.setBounds(60, 600, 220, 25);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/instrucoes.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-160, 0, 2340, 1490);

        jPanel1.setLayout(null);
        getContentPane().add(jPanel1);
        jPanel1.setBounds(-40, 0, 1540, 750);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_voltarparaomenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_voltarparaomenuActionPerformed
        
        new ShipRoyale03().setVisible(true);  //nome seria a classe principal que vc quer voltar
        this.dispose();
    }//GEN-LAST:event_button_voltarparaomenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Telainstrucoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Telainstrucoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Telainstrucoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Telainstrucoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Telainstrucoes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.TextArea Areadetexto;
    private javax.swing.JButton button_voltarparaomenu;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
